runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  mime_type: "text/css"
  static_dir: css

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
